Be-Secure/BeSman

src/main/bash/besman-create.sh
src/main/bash/besman-env-helpers.sh
src/main/bash/besman-main.sh
src/main/bash/besman-repo-helpers.sh

- Added file for create command.
- Updated main file to with create command and its options.
- Added repo helper file.
- updated env helper with format checks for cve & assessments.

Added files for create command

---

src/main/bash/besman-main.sh
src/main/bash/commands/besman-list.sh

Updated list command to list playbooks.

---

src/main/bash/besman-repo-helpers.sh
src/main/bash/commands/besman-help.sh
src/main/bash/commands/besman-pull.sh

- The pull command has been updated with proper output messages for the following scenarios,
1. If local playbook repo is upto date with remote playbook repo. - `Playbooks already upto date`
2. If local playbook repo is not upto date with remote playbook repo. - `Playbooks updated/added successsfully.`
3. Error while pulling. `Could not pull playbooks`
- Added function to clone repo quietly.
- Updated bes help with pull command

Pull command updated with proper output messages.

---

.github/workflows/dopublish.yml
bin/release.sh

- The action will be triggered when a tag is pushed of format `*.*.*`
- We use `BeSman/bin/release.sh` file for tagging the code and pushing the tag.
1. Clone the repo.
2. Swtich to a tmp branch
3. Change Be-Secure namespace to your namespace - `export BESMAN_NAMESPACE=<namespace>` 
4. Rename `master` branch into the name of the current branch under `bin/release.sh` file.
5. Execute the file - `./bin/release.sh <tag>`
6. Go to repository and switch to the tmp branch
7. Open actions and check the latest workflow under the name `Updating version of release to <tag>`
8. Check the `dist` folder under `dist` branch to see latest artifacts of BeSman.

Added github workflow for automated release for BeSman 

---

src/main/bash/besman-ansible-helpers.sh

- Done to pick up the home dir irrespective of the machine/user used.

Added var for home dir

---

scripts/tmpl/get.besman.io.tmpl
src/main/bash/besman-main.sh
src/main/bash/besman-utils.sh
src/main/bash/commands/besman-run.sh

command - `bes run --playbook <playbook> --input "arguments"`
Supports - yml, md, sh.

Added command run to execute playbooks

---

src/main/bash/commands/besman-help.sh

Updated bes help command

---

README.md
src/main/bash/besman-ansible-helpers.sh
src/main/bash/besman-env-helpers.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-uninstall.sh

Fixed issue #71 
**Testing**
Please use this [env](https://github.com/asa1997/test_repo_a/tree/master/template/0.0.1) for testing.
1. Setup
- Open .besman/etc/user-config.cfg
- Update `BESMAN_ENV_REPOS=asa1997/test_repo_a`
- Save.
- Run `source .besman/bin/besman-init.sh`
- Run `bes update`
- To view the updated list, run `bes list`
2. Using env level config.
- Install the env `template-env`, `$ bes install -env asa1997/test_repo_a/template-env -V 0.0.1`
- Check for o/p of variables.
- You can see the yml file in your home dir under the name - `besman-template-env.yml`
3. Using user level config.
- Uninstall the template-env.
- Open the config file - `besman-template-env.yml`
- Make some changes in the values.
- Save
- Install the template-env.
- Check the output for the changes.

Added env helper function to source env parameters from config file.

---

quick_install.sh
src/main/bash/commands/besman-list.sh
src/main/bash/scripts/besman-get-playbook-details.py

Fixed #95 : Updated list command to list playbooks

---

src/main/bash/commands/besman-list.sh

Fixed #104 : Added annotations for installed environments and remote environments

---

quick_install.sh
scripts/tmpl/get.besman.io.tmpl
src/main/bash/commands/besman-list.sh

Fixed #110: Display the local and remote availability of paybooks

---

README.md
src/main/bash/besman-playbook-helpers.sh
src/main/bash/scripts/besman-generate-osar.py

sonarqube and sbom is completed as of now.
We can generate OSAR for Sonarqube and SBOM.

bes osar generation script for bes playbook prepare function

---

src/main/bash/besman-main.sh
src/main/bash/commands/besman-pull.sh
src/main/bash/commands/besman-run.sh

Fixed #103 : Updated pull command to pull playbook

---

README.md
src/main/bash/besman-main.sh
src/main/bash/commands/besman-create.sh
src/main/bash/commands/besman-help.sh
src/main/bash/commands/besman-list.sh

The change has been made to match the other options such as environment and playbook

Renamed roles to role

---

.github/workflows/dopublish.yml
bin/dopublish.sh
bin/release.sh
scripts/tmpl/get.besman.io.tmpl

Fix #128 
To test 
1. Run
curl -L https://raw.githubusercontent.com/asa1997/BeSman/dist/dist/get.besman.io | bash
source "$HOME/.besman/bin/besman-init.sh"
3.  List playbooks
bes list --playbook

Fixed #128

---

src/main/bash/besman-env-helpers.sh
src/main/bash/commands/besman-create.sh
src/main/bash/commands/besman-install.sh

https://github.com/Be-Secure/BeSman/issues/132
Fixed hyphen (-) issue in ossp name. Now user can use hyphen in ossp name. BeSman will automatically detect the ossp name and it will create/install an env file with the exact ossp name as GitHub. No need to replace the hyphen (-) with an underscore (_).

Fixed hyphen (-) issue in ossp name

---

src/main/bash/commands/besman-create.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-reset.sh
src/main/bash/commands/besman-uninstall.sh
src/main/bash/commands/besman-update.sh
src/main/bash/commands/besman-validate.sh

Fix #137
__besman_install_[env name] - > __besman_install
__besman_uninstall_[env name] - > __besman_uninstall
.
.
.

Fixed #137 : Changed env lifecycle function names to align with the standarad

---

src/main/bash/besman-env-helpers.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-reset.sh

https://github.com/Be-Secure/BeSman/issues/132
Update.

Update: Fixed hyphen (-) issue in ossp name

---

src/main/bash/besman-env-helpers.sh
src/main/bash/commands/besman-create.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-reset.sh

Do a quick_install to test as this code is not released yet.

Added condition check for non rt/bt env

---

CODEOWNERS
CONTRIBUTING.md
checklist.md

Updated contributing file and added codeowners for highlighting reviewers for pull requests

Updated contributor's guidelines and added codeowners

---

src/main/bash/commands/besman-list.sh
src/main/bash/scripts/besman-generate-osar.py

Fixed #177 
Here is the sample result generated
```json
"results": [
{
"feature": "Attack",
"aspect": "evasion",
"attribute": "Success",
"value": true
}
]
```

Added osar for counterfit

---

src/main/bash/besman-env-helpers.sh
src/main/bash/commands/besman-list.sh

Fixed #148 : Function to check if env config parameters are empty

---

README.md
quick_install.sh
scripts/tmpl/get.besman.io.tmpl
src/main/bash/besman-env-helpers.sh
src/main/bash/commands/besman-help.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-list.sh
src/main/bash/commands/besman-reset.sh
src/main/bash/commands/besman-set.sh
src/main/bash/commands/besman-update.sh
src/main/bash/scripts/besman-get-env-list.py

This is the [json](https://github.com/asa1997/besecure-ce-env-repo/blob/develop/environment-metadata.json) from where we will list the envs.
Here is the output
Here is the output for local env

Fixed #203 : Listing enviornments using environment-metadata.json; Renamed env repo variable

---

README.md
src/main/bash/besman-env-helpers.sh
src/main/bash/besman-main.sh
src/main/bash/commands/besman-config.sh
src/main/bash/commands/besman-help.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-list.sh

Fixed #145: Added config command to download the env config file

---

src/main/bash/commands/besman-list.sh
src/main/bash/scripts/besman-get-env-list.py

Fixed #205: Error handling added for listing environments

---

src/main/bash/commands/besman-config.sh

Fixed #208: Bug while downloading config file

---

src/main/bash/besman-env-helpers.sh

Fixed #210: Bug due to not cleaning up after trap

---

quick_install.sh
src/main/bash/commands/besman-create.sh
src/main/bash/scripts/besman-generate-env-metadata.py

Fixed #168: Updated the create command to add env metadata to json file

---

quick_install.sh
src/main/bash/commands/besman-list.sh
src/main/bash/scripts/besman-get-env-list.py
src/main/bash/scripts/besman-get-playbook-details.py

Fixed #213: Listing only compatible playbooks of the installed environments

---

src/main/bash/commands/besman-list.sh
src/main/bash/scripts/besman-get-env-list.py

Fixed #214: Bug while listing local envs

---

README.md
scripts/tmpl/get.besman.io.tmpl
src/main/bash/besman-init.sh
src/main/bash/scripts/besman-generate-osar.py

1. The default installation would be latest stable release.
2. If user wishes to install a different release (rc/previous releases), they have to specify the version using export command.
3. The instructions for installation of BeSman has been updated.
4. Installation can now be done in a single step instead of the previous two step process.

Updated installation steps

---

src/main/bash/commands/besman-create.sh

Fixed #218: Added sanity check for spaces in author name

---

src/main/bash/commands/besman-list.sh
src/main/bash/scripts/besman-get-playbook-details.py

Fixed #222: Error while listing compatible playbooks for local envs

---

src/main/bash/besman-init.sh
src/main/bash/commands/besman-list.sh

Fixed #223: Bug while listing remote envs

---

src/main/bash/besman-env-helpers.sh
src/main/bash/commands/besman-install.sh

fixed #221: Displaying incorrect message for user configuration file

---

src/main/bash/scripts/besman-generate-osar.py

updated osar - added parser for cycloneDX sbom output

updated osar - added parser for cycloneDX sbom output

---

src/main/bash/scripts/besman-get-env-list.py

Fixed #228: Issue when listing envs from cloud instance

---

src/main/bash/besman-main.sh
src/main/bash/commands/besman-install.sh

Fixed #144: Updated install to fetch the latest version of env if not provided

---

quick_install.sh
scripts/tmpl/get.besman.io.tmpl
src/main/bash/commands/besman-help.sh
src/main/bash/commands/besman-list.sh
src/main/bash/commands/besman-run.sh
src/main/bash/scripts/besman-generate-osar.py
src/main/bash/scripts/besman-get-playbook-details.py

Run bes-playbook from local.
Added this features for developers to test the playbook without uploading them to github repo.

Run bes-playbook from local

---

src/main/bash/commands/besman-list.sh
src/main/bash/commands/besman-pull.sh
src/main/bash/commands/besman-run.sh
src/main/bash/scripts/besman-get-playbook-details.py

Fix: #235, #236, #237 
When testing, change the playbook repo to `asa1997/besecure-playbooks-store` and branch to `naming`

Fixed #235; #236; #237 : Made changes to accomodate the new playbook naming convention

---

quick_install.sh
scripts/tmpl/get.besman.io.tmpl
src/main/bash/besman-env-helpers.sh
src/main/bash/besman-repo-helpers.sh
src/main/bash/commands/besman-config.sh
src/main/bash/commands/besman-create.sh
src/main/bash/commands/besman-help.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-list.sh
src/main/bash/commands/besman-pull.sh
src/main/bash/commands/besman-run.sh
src/main/bash/commands/besman-set.sh
src/main/bash/scripts/besman-get-env-list.py
src/main/bash/scripts/besman-get-playbook-details.py
src/main/bash/scripts/besman_python_helper.py

Fix #242; #241; #236

---

quick_install.sh
scripts/tmpl/get.besman.io.tmpl
src/main/bash/besman-env-helpers.sh
src/main/bash/besman-path-helpers.sh
src/main/bash/besman-repo-helpers.sh
src/main/bash/besman-utils.sh
src/main/bash/commands/besman-config.sh
src/main/bash/commands/besman-help.sh
src/main/bash/commands/besman-install.sh
src/main/bash/commands/besman-list.sh
src/main/bash/commands/besman-pull.sh
src/main/bash/scripts/besman-get-env-list.py
src/main/bash/scripts/besman-get-playbook-details.py
src/main/bash/scripts/besman_python_helper.py

Fixed #248: Issue when listing envs from private gitlab repo

---

src/main/bash/besman-env-helpers.sh

Fixed #249: Issue while reloading env configurations in local mode

---

src/main/bash/scripts/besman-generate-osar.py

Fixed #252: Issue with generating OSAR

---

src/main/bash/besman-env-helpers.sh

Fixed #254: Issue when uninstalling env in local mode

---

quick_install.sh
scripts/tmpl/get.besman.io.tmpl

updated jupyter installation steps

updated jupyter notebook installation
